Fixed: rails(api-mode) crashed in starting (#21)
api mode doesn't have `Rails.application.config.assets`

```
rails aborted!
NoMethodError: undefined method `assets' for #<Rails::Application::Configuration:0x007f92c8731ee8>
Did you mean?  asset_host
/app/config/environment.rb:5:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
```